CREATE TABLE type
(
    id VARCHAR(32) NOT NULL
        PRIMARY KEY COMMENT '类别ID',
    name VARCHAR(128) NOT NULL COMMENT '类别名称'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT '类别表';