CREATE TABLE tag
(
    id VARCHAR(32) NOT NULL
        PRIMARY KEY COMMENT '标签ID',
    name VARCHAR(128) NOT NULL COMMENT '标签名称'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin COMMENT '标签表';